name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.3, 2.4, 2.5, 2.6, 2.7, 3.0]
        gemfile: ['rails50', 'rails51', 'rails52', 'rails60', 'rails61']
        exclude:
          - ruby: 2.3
            gemfile: rails60
          - ruby: 2.3
            gemfile: rails61
          - ruby: 2.4
            gemfile: rails60
          - ruby: 2.4
            gemfile: rails61
          - ruby: 3.0
            gemfile: rails50
          - ruby: 3.0
            gemfile: rails51
          - ruby: 3.0
            gemfile: rails52

    name: ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}, ${{ matrix.database }}

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run test
      run: |
        bundle exec rspec spec/slonik_migration_spec.rb
        bundle exec rspec spec/slonik_migration_task_spec.rb
